version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/python-calculator-docker

hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/run_docker.sh
      timeout: 300
      runas: ubuntu
